dist: trusty
language: php
php:
- 5.5
- 5.6
- 7.0
- 7.1
git:
  depth: 5
script:
- php -l *.php
deploy:
  skip_cleanup: true
  provider: script
  script: deploy/deploy.sh $TRAVIS_TAG
  on:
    tags: true
    branch: master
env:
  global:
  - secure: AcQ0NqbQMyhBkFkLXoXo5f++2KlT7+3ICdXRkiG8h07BpoelN4zoRAQTSPJIaKetLwdNJjY6+bLR6ZeQP3CQxKfectpXZBU3b7Ae5MqP773DoOe3cRtm5Ns0PtePI/I5XWZc5rOaCXB6ax5wn+bVqPlX0ercensU0z+EGgpSEAkAnblAvT2btHzO2IJOHEYe2OUgsHHjHShkNhF2fcPS0T8kCkDUX79D4BzPSkro3SL4JfvTBUOThIHVLYivjvCNOhAhqVCKow5ykR1yKoUYF8uvbsSR6HTuZpSxOpRgy8+gD24RZ56pTsF9krK33uSFhHWRl/+j2jVztKquT9np0/fuaFbNzmIwyX7gf87qhyvBebzvEiAgFDGK8Fs47uA5S+xx1sWGL02BkCIyQZz88VAgmCBxf6Y9kf9YcKWKMMwzs9Q9PGzlDRMfK80iR21ddbxdjD0LtyCSMFrQ70J99F25MWKOyE8MJcB3DqEUhOcZcdvFg1gkGmNzaP57tUukEXNNsyJWfir2xcDKecZiiG6llqo6uQaoqk2r/QhKghuulMZpcudnYpGhkpiFDoF5pq0jp92R6AS24Ps+9YGthIVA07sZHsJDLbthZLlrTkB4FGFSEvisi/A18dDt9ijAX9U6257QSzJuYjbKgeXQcY3g0yGzwgTpLWad5NIqgp8=
  - secure: wtrOJumA5z1CZ9bl7/fcETviHNd42KgZdrm26PYagFK49vGPbw33iodBEun+jhpmHLCZjztiJ611o2oKPpZCsL2z6HNaXdQHxwmsYkI8bbHROp7GgQAJ/jnrE3//v3oiAd5pWlWWdz5jxbv3ZGDlm4OHcF+ZYAGlYQNYjT6tppu67ggkw+yT5gIONq84hnNRb9Vh3LNs17nzVsmjDVIEp4u/ofJbqpjjuLwPnjK5yz/uSj5ZbSwMD06U/QTj6dCRdA80DOuVALqPrOHf5sIhSHKJLsATY632Kyi6ihpHExLq1sk7Xs3R/kHp9RpzMXflXc8Ald9BZdEEXSZKfWnFxPGyy4AtRGtxA79qQ8pbr+c5LDiKy4Dsh+KAefZIbocbM7x/gkz2r2VCz9oF41DrQWw3Cc3r6tv0NiwKumUlGfrPLM1KFdHctGNITBNyneUwktWKBFkXWTQTaSuTkfEqXOyeFvKC3G01GHewDFtuZ7bqbgJv/U9kII71WmiEYzDVaoWBOD1H1k1WKc1JekKDg4pVYwDqIp9mONPlFEsJ7TR5pvulH4zmVkJUBUKcUGqJZKMHbNCCh+cVIcnIVGxPb5vcvFEbYpXqaHTKf+re7KnXgLBYjehiQx4AgqrlrIWKhqc2vvK9lfcZNNFELndE3F7K1s8HDHhDINlLZMK5eRA=
  - secure: fm0jN2lY1UdLvKxNrcGR/2EO6blAkkQl4u7zi5Jvj/L9WuAWULKy4/4wlFiFa2ZEp7llVqD8/aSmlPkEgdqvNO+VN2lsk1HvoK58O7SlaC+Cald/Q2QONaNQXQkn8kBAq0qn01op1cgLEWHZCNOmYJ5apVbbOGdMLlj6JoR8fIIysWMpv0ZVpeEp4LvvU0DNaMJofRFpzPI67LTOrw53B/sCJTo16iossUh02r4mqAUhKHDDZyG/BoPUgefhb8h6fCCirg/e5D1HPIXqYbcA3Q7ELcXr06pmRlHTihE6vfSSbAvRKzn95PB4Km0G6s1t9RValORWgcIJKU4TyxLSfQ/1wWP3yTRjseczs23P3cePc41O0LzYmk38ZqiDnfQofJJ2hID5TnJFj2mQbCkP3OLyhNaovk+F2vUQZhKS3ZInbATFYXlRAUkSsIIrrFBvN9cfG9LQ5vRoLFtOhMjKxRAvn5bzNH/tEwG9xnnNnbnZ9IUEXSXZbAu5+OVH55HTGOsAQYzigto1jXAiwfE+BM1mR/y5ozD6hz9DLLJ4FLh6Pg23u8snvr5jrqw57FG0/QRoXEZwVVs8Gy6RYns/wufh5xDSAS/en+XCVS+m/A4n/7+3Zms6GOE6ytW78AbKrZOE4fzgSy3rNpT+huWyMam02sx1+hR0PGkkZCNjubc=
