name: Pre-build Checks
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]
jobs:
  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['7.1', '8.3']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - name: Run Linter
        run: |
          php -l src/inline-spoilers.php
  codesniffer:
    name: Code Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Setup CodeSniffer
        run: |
          composer install
      - name: Check WordPress Coding Standards
        run: |
          ./vendor/bin/phpcs --standard=WordPress --extensions=php ./src/
