name: Trunk Sync
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
on:
  push:
    branches: [master]
jobs:
  deploy:
    name: Renew Metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get WordPress Repository
        env:
          SVN_REPOSITORY: ${{ vars.SVN_REPOSITORY }}
        run: |
          svn co $SVN_REPOSITORY ${{ runner.temp }}/svn
      - name: Prepare Repository
        run: |
          cp -R ./plugin/* ${{ runner.temp }}/svn/trunk/
          cp -R ./assets/* ${{ runner.temp }}/svn/assets/
          cd ${{ runner.temp }}/svn/trunk/
          svn add --force .
      - name: Publish Changes
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_COMMIT_MESSAGE: "Metadata Sync"
        run: |
          cd ${{ runner.temp }}/svn
          svn ci  --message "$SVN_COMMIT_MESSAGE" \
                  --username $SVN_USERNAME \
                  --password $SVN_PASSWORD \
                  --non-interactive \
                  --trust-server-cert
                  
